### ISSUE TITLE
Issue with ROC curve

### ISSUE THREAD

**Issue by raiza97** [NeuromorphicComputationResearchProgram/MalConv2#4]
Hi, how can I plot the roc curve with truths and preds? I've tried with this code but I get a curve with a "triangular" shape

fig, ax = plt.subplots()
ax.set_xlabel("False Positive Rate")
ax.set_ylabel("True Positive Rate")
fpr, tpr, _ = roc_curve(truths, preds)
auc_score = roc_auc_score(truths, preds)
ax.plot(fpr, tpr, label=f"{save_title} ({auc_score:.3f})")
ax.plot([0.0, 1.0], [0.0, 1.0], linestyle="--", label="Chance (0.5)")
fig.savefig(os.path.join("imgs", f"{save_title}_roc.png"))
plt.close(fig)
![nocat_MalConvGCT_channels_256_filterSize_256_stride_64_embdSize_8_roc](https://user-images.githubusercontent.com/58850706/192096240-d1178db9-8e20-4e32-a5fe-6c7467abfd28.png)

**Comment by EdwardRaff** [comment]
What is the issue exactly? The code seems to be correct to produce a ROC curve, and the curve is to the upper left - above the random-guessing line. So it looks like it is working?

**Comment by raiza97** [comment]
Typically there are some steps (based on tresholds used by **roc_auc_score** function). For example:
![roc_curve_python](https://user-images.githubusercontent.com/58850706/192143698-37d8ea35-1f6b-40cf-b464-cc8d83183a6e.png)

So, my question is: it is an error to have a flat ROC?

**Comment by raiza97** [comment]
Solved, there was an error in the preds vector.
